# Generated by Django 4.2.20 on 2025-11-20 20:28

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('buildings', '0017_alter_buildingfloor_floor_num'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=3857)),
                ('line_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('elevator', 'Elevator'), ('elevator-no-floor-change', 'Elevator (no floor change)'), ('stairs', 'Stairs'), ('stairs-no-floor-change', 'Stairs (no floor change)'), ('ramps', 'Ramps')], max_length=32)),
                ('is_private', models.BooleanField(default=False, help_text='If true, this edge is only usable in private routes.')),
                ('source_node_id', models.BigIntegerField(blank=True, help_text='pgRouting source node id', null=True)),
                ('target_node_id', models.BigIntegerField(blank=True, help_text='pgRouting target node id', null=True)),
                ('cost', models.FloatField(default=0.0)),
                ('reverse_cost', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_edges', to='buildings.building')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_edges', to='campus.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_edges_created', to=settings.AUTH_USER_MODEL)),
                ('floor_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_edges_from', to='buildings.buildingfloor')),
                ('floor_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_edges_to', to='buildings.buildingfloor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_edges_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routing_edge',
                'indexes': [models.Index(fields=['campus', 'building', 'floor_from', 'floor_to'], name='routing_edg_campus__e032c4_idx'), models.Index(fields=['line_type'], name='routing_edg_line_ty_0186c8_idx'), models.Index(fields=['is_private'], name='routing_edg_is_priv_3c05e9_idx')],
            },
        ),
    ]
