version: '3'
volumes:
  indrz-cloud-postgis:
  indrz-cloud-geoserver:
  indrz-cloud-pgadmin-data:
networks:
  indrz-cloud-net:

services:
  indrz_cloud_api:
    container_name: indrz_cloud_api
    image: indrz-cloud-api:3.0
    build:
      context: ./indrz
      dockerfile: ./devops/docker/indrz
    ports:
      - 8000:8000
    depends_on:
      - indrz_cloud_postgis
    volumes:
      - ./indrz:/app
      - ./data/dwg:/app/scripts/geodata/dwg
    restart: always
    networks:
      - indrz-cloud-net
    env_file:
      - .env
  indrz_cloud_geoserver:
    container_name: indrz_cloud_geoserver
    image: kartoza/geoserver:2.21.1
    volumes:
     - indrz-cloud-geoserver:/opt/geoserver/data_dir
    ports:
     - 8080:8080
    restart: on-failure
    networks:
      - indrz-cloud-net
    env_file:
     - .env
    healthcheck:
     test: curl --fail -s http://localhost:8080/ || exit 1
     interval: 1m30s
     timeout: 10s
     retries: 3
    depends_on:
      - indrz_cloud_postgis
  indrz_cloud_pgadmin:
    container_name: indrz_cloud_pgadmin
    image: dpage/pgadmin4:latest
    volumes:
      - indrz-cloud-pgadmin-data:/var/lib/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gomogi.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    networks:
      - indrz-net-boku
    links:
      - "indrz_cloud_postgis:pgsql-server"
    depends_on:
      - indrz_cloud_postgis
  indrz_cloud_postgis:
    container_name: indrz_cloud_postgis
    image: kartoza/postgis:13.0
    volumes:
      - indrz-cloud-postgis:/var/lib/postgresql
    ports:
      - 5432:5432
    env_file:
      .env
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
    restart: on-failure
    networks:
      - indrz-cloud-net
    healthcheck:
      test: "exit 0"