version: '3'
volumes:
  indrz-local-db:
  indrz-local-geoserver:
  indrz-local-pgadmin:
networks:
  indrz-net:

services:
  indrz_api:
    container_name: indrz_api
    image: indrz_api:latest
    build:
      context: ./indrz
      dockerfile: ./devops/docker/local/indrz_api
    ports:
      - 8000:8000
    depends_on:
      - indrz_db
    volumes:
      - ./indrz:/app
      - ./data/dwg:/app/scripts/geodata/dwg
    restart: always
    networks:
      - indrz-net
    env_file:
      - .env
  indrz_geoserver:
    container_name: indrz_geoserver
    image: kartoza/geoserver:2.23.0
    volumes:
     - indrz-local-geoserver:/opt/geoserver/data_dir
    ports:
     - 8080:8080
    restart: on-failure
    networks:
      - indrz-net
    env_file:
     - .env
    healthcheck:
     test: curl --fail -s http://localhost:8080/ || exit 1
     interval: 1m30s
     timeout: 10s
     retries: 3
    depends_on:
      - indrz_db
  indrz_pgadmin:
    container_name: indrz_pgadmin
    image: dpage/pgadmin4:latest
    volumes:
      - indrz-local-pgadmin:/var/lib/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gomogi.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    networks:
      - indrz-net
    links:
      - "indrz_db:pgsql-server"
    depends_on:
      - indrz_db
  indrz_db:
    container_name: indrz_db
    image: kartoza/postgis:15-3.3
    volumes:
      - indrz-local-db:/var/lib/postgresql
    ports:
      - 5432:5432
    env_file:
      .env
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
    restart: on-failure
    networks:
      - indrz-net
    healthcheck:
      test: "exit 0"