# Generated by Django 4.2.19 on 2025-02-26 06:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Campus name')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Building description')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Campus area of one or more buildings')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Display order')),
                ('fk_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
