# Generated by Django 4.2.16 on 2025-01-19 11:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('street', models.CharField(blank=True, max_length=256, null=True, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Building or house number')),
                ('postal_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Postal code')),
                ('municipality', models.CharField(blank=True, max_length=256, null=True, verbose_name='Municipality')),
                ('city', models.CharField(blank=True, max_length=256, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=256, null=True, verbose_name='Country')),
                ('description', models.TextField(blank=True, help_text='Brief description', null=True, verbose_name='Description')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=256, null=True, verbose_name='Website')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=3857, verbose_name='Building centroid for small scale maps')),
                ('owner', models.CharField(blank=True, max_length=128, null=True, verbose_name='Owner name')),
                ('legal_form', models.CharField(blank=True, max_length=128, null=True, verbose_name='Legal entity form')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
