# Generated by Django 4.2.16 on 2025-01-19 11:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('street', models.CharField(blank=True, max_length=256, null=True, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Building or house number')),
                ('postal_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Postal code')),
                ('municipality', models.CharField(blank=True, max_length=256, null=True, verbose_name='Municipality')),
                ('city', models.CharField(blank=True, max_length=256, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=256, null=True, verbose_name='Country')),
                ('description', models.TextField(blank=True, help_text='Brief description', null=True, verbose_name='Description')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=256, null=True, verbose_name='Website')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=3857, verbose_name='Building centroid for small scale maps')),
                ('name_en', models.TextField(blank=True, null=True)),
                ('name_de', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('ext_dept_id', models.IntegerField(blank=True, null=True)),
                ('ext_dept_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ext_parent_dept_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ext_parent_dept_id', models.IntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
