# Generated by Django 2.2.5 on 2019-10-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='floor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='floor name'),
        ),
    ]
