# Generated by Django 2.2.5 on 2019-10-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi_manager', '0002_poi_floor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='floor_num',
            field=models.FloatField(blank=True, null=True, verbose_name='floor number'),
        ),
    ]
