# Generated by Django 2.2.6 on 2019-11-13 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poi_manager', '0003_auto_20191018_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='fk_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.Campus'),
        ),
    ]
