# Generated by Django 2.2.6 on 2019-11-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poi_manager', '0004_auto_20191113_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='fk_campus',
        ),
    ]
