# Generated by Django 3.1.13 on 2021-09-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poi_manager', '0015_poicategory_html_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poicategory',
            old_name='html_field',
            new_name='html_content',
        ),
    ]
