# Generated by Django 4.2.19 on 2025-02-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi_manager', '0019_auto_20230117_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poiimages',
            options={'ordering': ['sort_order']},
        ),
        migrations.RenameField(
            model_name='poiimages',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='poiimages',
            name='thumbnails',
        ),
        migrations.AddField(
            model_name='poi',
            name='html_content',
            field=models.TextField(blank=True, null=True, verbose_name='HTML content'),
        ),
        migrations.AddField(
            model_name='poi',
            name='html_content_de',
            field=models.TextField(blank=True, null=True, verbose_name='DE HTML content'),
        ),
        migrations.AddField(
            model_name='poicategory',
            name='html_content_de',
            field=models.TextField(blank=True, null=True, verbose_name='DE HTML content'),
        ),
        migrations.AddField(
            model_name='poiimages',
            name='alt_text',
            field=models.CharField(default='Image of ...', max_length=255, verbose_name='Html image alt text'),
        ),
        migrations.AddField(
            model_name='poiimages',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poiimages',
            name='sort_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Order of images'),
        ),
        migrations.AddField(
            model_name='poiimages',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, max_length=512, null=True, upload_to='poi_images', verbose_name='POI Image Thumbnail'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='poicategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='poiicon',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='poiimages',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
