# Generated by Django 2.2.5 on 2019-09-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='wings',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Wing'),
        ),
    ]
