# Generated by Django 2.2.5 on 2019-09-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_building_wings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingfloor',
            name='floor_num',
            field=models.FloatField(blank=True, null=True, verbose_name='floor number'),
        ),
    ]
