# Generated by Django 2.2.5 on 2019-10-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_wing'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingfloorspace',
            name='floor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='floor name'),
        ),
        migrations.AddField(
            model_name='interiorfloorsection',
            name='floor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='floor name'),
        ),
    ]
