# Generated by Django 2.2.5 on 2019-09-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_auto_20190920_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingfloorspace',
            name='fk_building',
        ),
        migrations.RemoveField(
            model_name='interiorfloorsection',
            name='fk_building',
        ),
    ]
