# Generated by Django 2.2.5 on 2019-09-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20190921_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingfloorspace',
            name='floor_num',
            field=models.FloatField(blank=True, null=True, verbose_name='floor number'),
        ),
        migrations.AlterField(
            model_name='interiorfloorsection',
            name='floor_num',
            field=models.FloatField(blank=True, null=True, verbose_name='floor number'),
        ),
    ]
