# Generated by Django 2.2.6 on 2019-11-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_buildingfloor_floor_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingfloorspace',
            options={'ordering': ['room_code']},
        ),
        migrations.RemoveField(
            model_name='buildingfloorspace',
            name='tags',
        ),
    ]
