# Generated by Django 2.2.5 on 2019-09-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_auto_20190921_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingfloorplanline',
            name='fk_building',
        ),
    ]
