# Generated by Django 2.2.5 on 2019-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_remove_buildingfloorplanline_fk_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingfloorplanline',
            name='floor_num',
            field=models.FloatField(blank=True, null=True, verbose_name='floor number'),
        ),
    ]
