# Generated by Django 2.2.6 on 2019-12-08 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_buildingfloorplanline_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wing',
            name='building',
        ),
        migrations.AddField(
            model_name='wing',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='gis calculated area'),
        ),
        migrations.AddField(
            model_name='wing',
            name='fk_access_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.LtAccessType'),
        ),
        migrations.AddField(
            model_name='wing',
            name='fk_building_floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buildings.BuildingFloor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wing',
            name='floor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='floor name'),
        ),
        migrations.AddField(
            model_name='wing',
            name='floor_num',
            field=models.FloatField(blank=True, null=True, verbose_name='floor number'),
        ),
        migrations.AddField(
            model_name='wing',
            name='long_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='long name'),
        ),
        migrations.AddField(
            model_name='wing',
            name='perimeter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='gis calculated perimeter'),
        ),
        migrations.AddField(
            model_name='wing',
            name='short_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='short name'),
        ),
    ]
