# Generated by Django 3.1.13 on 2021-08-29 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poi_manager', '0014_auto_20210829_1249'),
        ('buildings', '0010_buildingfloor_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingfloorspace',
            name='fk_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
        migrations.AddField(
            model_name='interiorfloorsection',
            name='fk_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
        migrations.AddField(
            model_name='interiorfloorsection',
            name='rule_nearest_entrance',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 13}, to='poi_manager.Poi'),
        ),
        migrations.AddField(
            model_name='wing',
            name='fk_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
    ]
