# Generated by Django 3.1.13 on 2021-09-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_auto_20210829_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Display order'),
        ),
    ]
