# Generated by Django 4.2.19 on 2025-02-26 06:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('poi_manager', '0020_alter_poiimages_options_and_more'),
        ('buildings', '0014_auto_20230117_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingfloor',
            name='name_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='name such as EG'),
        ),
        migrations.AddField(
            model_name='buildingfloor',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='name such as EG'),
        ),
        migrations.AddField(
            model_name='buildingfloorplanline',
            name='fk_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
        migrations.AddField(
            model_name='buildingfloorspace',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(re.compile('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$'), 'Enter a valid hex color, eg. #000000', 'invalid')], verbose_name='Hex Color'),
        ),
        migrations.AddField(
            model_name='buildingfloorspace',
            name='nearest_entrance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poi_manager.poi'),
        ),
        migrations.AddField(
            model_name='interiorfloorsection',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(re.compile('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$'), 'Enter a valid hex color, eg. #000000', 'invalid')], verbose_name='Hex Color'),
        ),
        migrations.AddField(
            model_name='wing',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(re.compile('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$'), 'Enter a valid hex color, eg. #000000', 'invalid')], verbose_name='Hex Color'),
        ),
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buildingfloor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buildingfloorplanline',
            name='fk_line_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.ltplanlinetype'),
        ),
        migrations.AlterField(
            model_name='buildingfloorplanline',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buildingfloorspace',
            name='fk_access_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.ltaccesstype'),
        ),
        migrations.AlterField(
            model_name='buildingfloorspace',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buildingfloorspace',
            name='space_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.ltspacetype'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='interiorfloorsection',
            name='fk_access_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.ltaccesstype'),
        ),
        migrations.AlterField(
            model_name='interiorfloorsection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ltaccesstype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ltcondition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ltplanlinetype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ltspacetype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wing',
            name='fk_access_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.ltaccesstype'),
        ),
        migrations.AlterField(
            model_name='wing',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
