# Generated by Django 4.2.19 on 2025-02-26 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('organizations', '0002_department'),
        ('buildings', '0015_buildingfloor_name_de_buildingfloor_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='fk_campus',
        ),
        migrations.RemoveField(
            model_name='building',
            name='fk_organization',
        ),
        migrations.RemoveField(
            model_name='interiorfloorsection',
            name='department',
        ),
        migrations.RemoveField(
            model_name='interiorfloorsection',
            name='organization',
        ),
        migrations.AddField(
            model_name='building',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='building',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
            preserve_default=False,
        ),
    ]
