# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 06:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0003_auto_20191018_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, verbose_name='External Shelf ID')),
                ('measure_from', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Measure FROM value')),
                ('measure_to', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Measure TO value')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, db_column='geom', null=True, spatial_index=False, srid=3857, verbose_name='Geometry of shelf')),
                ('left_from_label', models.CharField(blank=True, help_text='Map left label range shown on the 2d map', max_length=150, null=True, verbose_name='left from label')),
                ('left_to_label', models.CharField(blank=True, help_text='Map left label range shown on the 2d map', max_length=150, null=True, verbose_name='left to label')),
                ('right_from_label', models.CharField(blank=True, help_text='Map right label range shown on the 2d map', max_length=150, null=True, verbose_name='right from label')),
                ('right_to_label', models.CharField(blank=True, help_text='Map right label range shown on the 2d map', max_length=150, null=True, verbose_name='right to label')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building')),
                ('building_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.BuildingFloor')),
            ],
        ),
        migrations.CreateModel(
            name='ShelfData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=150, verbose_name='External Shelf ID')),
                ('floor', models.IntegerField(null=True, verbose_name='Floor Number')),
                ('section', models.CharField(help_text='A section located within a single shelf', max_length=150, null=True, verbose_name='External Shelf Section')),
                ('system_from', models.CharField(max_length=150, verbose_name='Shelving System Start Value')),
                ('system_to', models.CharField(max_length=150, verbose_name='Shelving System End Value')),
                ('side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=10, null=True, verbose_name='Left or Right side')),
                ('measure_from', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Distance from measure')),
                ('measure_to', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Distance end measure')),
                ('bookshelf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookway.BookShelf')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.Building')),
                ('building_floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.BuildingFloor')),
            ],
        ),
    ]
