# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 15:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfdata',
            name='sys_from_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150, null=True), size=None), null=True, size=None),
        ),
        migrations.AddField(
            model_name='shelfdata',
            name='sys_to_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150, null=True), size=None), null=True, size=None),
        ),
    ]
