# Generated by Django 3.1.13 on 2021-07-27 05:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookway', '0002_auto_20190127_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='depth in cm of bookshelf'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='double_faced',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Does the shelf have two sides'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='length in cm of bookshelf'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='rotation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rotation angle of the bookshelf'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='width in cm of bookshelf'),
        ),
        migrations.AddField(
            model_name='shelfdata',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shelfdata',
            name='section_child',
            field=models.CharField(blank=True, help_text='Library Code for a sub- section', max_length=150, null=True, verbose_name='Sub Section'),
        ),
        migrations.AddField(
            model_name='shelfdata',
            name='section_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Section id'),
        ),
        migrations.AddField(
            model_name='shelfdata',
            name='section_main',
            field=models.CharField(blank=True, help_text='Library Code for a section with multiple shelves', max_length=150, null=True, verbose_name='Main Section'),
        ),
        migrations.AddField(
            model_name='shelfdata',
            name='system_from_jsonb',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelfdata',
            name='system_to_jsonb',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
