# Generated by Django 3.1.13 on 2021-07-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookway', '0003_auto_20210727_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfdata',
            name='system_from_jsonb',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shelfdata',
            name='system_to_jsonb',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
