# Generated by Django 3.1.13 on 2021-07-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookway', '0004_auto_20210727_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='depth in m of bookshelf'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='length in m of bookshelf'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='width in m of bookshelf'),
        ),
    ]
