# Generated by Django 3.1.13 on 2021-07-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookway', '0005_auto_20210729_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='measure_from',
        ),
        migrations.RemoveField(
            model_name='bookshelf',
            name='measure_to',
        ),
    ]
