# Generated by Django 3.1.13 on 2021-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookway', '0006_auto_20210729_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfdata',
            name='measure_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Distance from measure'),
        ),
        migrations.AlterField(
            model_name='shelfdata',
            name='measure_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Distance end measure'),
        ),
        migrations.AlterField(
            model_name='shelfdata',
            name='section',
            field=models.CharField(blank=True, help_text='A section located within a single shelf', max_length=150, null=True, verbose_name='External Shelf Section'),
        ),
    ]
