# Generated by Django 3.1.13 on 2021-07-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookway', '0007_auto_20210729_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='double_faced',
            new_name='double_sided',
        ),
    ]
