# Generated by Django 3.1.13 on 2021-07-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookway', '0008_auto_20210730_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelfdata',
            name='section_id',
        ),
    ]
