# Generated by Django 4.2.20 on 2025-05-18 07:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.fields import ArrayField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(unique=True)),
                ('table_raw', models.TextField()),
                ('mtime', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building_code', models.TextField(blank=True, null=True)),
                ('floor_name', models.TextField(blank=True, null=True)),
                ('floor_number', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'File Registry',
                'verbose_name_plural': 'File Registries',
            },
        ),
        migrations.CreateModel(
            name='GeorefParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_raw', models.TextField()),
                ('x_org', models.FloatField(blank=True, null=True)),
                ('y_org', models.FloatField(blank=True, null=True)),
                ('x_geo', models.FloatField(blank=True, null=True)),
                ('y_geo', models.FloatField(blank=True, null=True)),
                ('scale', models.FloatField(default=1.0)),
                ('rotate', models.FloatField(default=0.0, help_text='degrees')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geom_georef', django.contrib.gis.db.models.fields.PointField(blank=True, db_column='geom', null=True, srid=3857)),
                ('FileRegistry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='georef_params', to='dxf_loader.fileregistry')),
            ],
            options={
                'verbose_name': 'Georeferencing Parameter',
                'verbose_name_plural': 'Georeferencing Parameters',
            },
        ),
        migrations.CreateModel(
            name='DxfLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', ArrayField(base_field=models.TextField(), default=list, help_text='List of layer names', blank=False, null=False, size=None),),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('FileRegistry', models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, related_name='dxf_layers', to='dxf_loader.fileregistry')),
            ],
            options={
                'verbose_name': 'DXF Layer',
                'verbose_name_plural': 'DXF Layers',
            },
        ),
        migrations.CreateModel(
            name='DxfImportedTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.TextField()),
                ('schema_name', models.TextField(default='dxf_raw')),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('srid', models.IntegerField(blank=True, null=True)),
                ('has_georef', models.BooleanField(default=False, help_text='Indicates if this raw table has been georeferenced')),
                ('georef_table_name', models.TextField(blank=True, null=True)),
                ('file_registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_tables', to='dxf_loader.fileregistry')),
            ],
            options={
                'verbose_name': 'DXF Imported Table',
                'verbose_name_plural': 'DXF Imported Tables',
            },
        ),
    ]
