# Generated by Django 4.2.20 on 2025-05-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_buildingfloor_name_de_buildingfloor_name_en_and_more'),
        ('dxf_loader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileregistry',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_registry', to='buildings.building'),
        ),
    ]
