# Generated by Django 4.2.20 on 2025-05-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxf_loader', '0002_fileregistry_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxflayer',
            name='type',
            field=models.CharField(blank=True, choices=[('spaces', 'Spaces'), ('doors', 'Doors'), ('stairs', 'Stairs'), ('ramp', 'Ramp'), ('innerwall', 'Inner Wall'), ('outerwall', 'Inner Wall'), ('furniture', 'Furniture')], default='spaces', max_length=16, null=True),
        ),
    ]
