# Generated by Django 4.2.20 on 2025-05-18 11:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dxf_loader', '0003_dxflayer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dxflayer',
            name='type',
            field=models.CharField(blank=True, choices=[('spaces', 'Spaces'), ('doors', 'Doors'), ('stairs', 'Stairs'), ('ramp', 'Ramp'), ('innerwall', 'Inner Wall'), ('outerwall', 'Outer Wall'), ('furniture', 'Furniture')], default='furniture', max_length=16, null=True),
        ),
    ]
