# Generated by Django 4.2.20 on 2025-11-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxf_loader', '0005_alter_dxflayer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dxflayer',
            name='type',
            field=models.CharField(blank=True, choices=[('spaces', 'Spaces'), ('uniqueid', 'Unique ID'), ('doors', 'Doors'), ('stairs', 'Stairs'), ('elevator', 'Elevator'), ('ramp', 'Ramp'), ('innerwall', 'Inner Wall'), ('outerwall', 'Outer Wall'), ('furniture', 'Furniture')], default='furniture', max_length=16, null=True),
        ),
    ]
