# Generated by Django 2.2.5 on 2019-10-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_auto_20191018_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingfloor',
            name='floor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='floor name'),
        ),
    ]
