# Generated by Django 3.1.13 on 2021-09-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_campus_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['sort_order']},
        ),
    ]
