# Generated by Django 4.2.20 on 2025-09-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0016_remove_building_fk_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingfloor',
            name='floor_num',
            field=models.FloatField(default=0, verbose_name='floor number'),
        ),
    ]
