# Generated by Django 2.2.6 on 2019-11-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_auto_20191113_2015'),
        ('poi_manager', '0005_remove_poi_fk_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='fk_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.Campus'),
        ),
    ]
