# Generated by Django 2.2.6 on 2019-11-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi_manager', '0009_auto_20191122_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
