# Generated by Django 3.1.5 on 2021-01-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi_manager', '0012_auto_20191207_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poiicon',
            old_name='poi_icon',
            new_name='icon',
        ),
        migrations.AlterField(
            model_name='poi',
            name='enabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Activated and enabled'),
        ),
        migrations.AlterField(
            model_name='poicategory',
            name='enabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Activated and enabled'),
        ),
        migrations.AlterField(
            model_name='poicategory',
            name='force_mid_point',
            field=models.BooleanField(blank=True, null=True, verbose_name='Force route to this location'),
        ),
    ]
