# Generated by Django 3.2.16 on 2023-01-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poi_manager', '0017_auto_20210909_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoiImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(max_length=512, upload_to='poi_images', verbose_name='POI images')),
                ('thumbnails', models.ImageField(blank=True, max_length=512, null=True, upload_to='poi_thumbnails', verbose_name='POI Image Thumbnail')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi_manager.poi')),
            ],
        ),
    ]
