# Generated by Django 4.2.14 on 2024-07-31 12:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zoneplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mainuse', models.CharField(max_length=100)),
                ('orgcode', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('room_code', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=100)),
                ('org_color', models.CharField(max_length=100)),
                ('mainuse_color', models.CharField(max_length=100)),
                ('surface_type_id', models.CharField(max_length=100)),
                ('secondary_users', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, db_column='geom', null=True, srid=3857)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
