# Generated by Django 4.2.15 on 2024-09-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoneplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoneplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
