apiVersion: v1
kind: Secret
metadata:
  name: indrz-api
type: Opaque
stringData:
  ALLOWED_HOSTS: "*"
  DEBUG: "True"
  INDRZ_API_TOKEN: "Token TODO"
  LOGFILE_DIR: /logs/
  MEDIA_ROOT: /opt/data/media
  MEDIA_URL: /media/
  SECRET_KEY: 'TODO'
  SENTRY_URL: https://secrethashurlfromsentry
  STATIC_FOLDER: /opt/data/static
  STATIC_ROOT: /opt/data/static
  STATIC_URL: /static/
---
apiVersion: v1
kind: Secret
metadata:
  name: geoserver
type: Opaque
stringData:
  ENABLE_JSONP: "true"
  FOOTPRINTS_DATA_DIR: "/opt/footprints_dir"
  GEOSERVER_ADMIN_PASSWORD: "TODO"
  GEOSERVER_DATA_DIR: "/opt/geoserver/data_dir"
  GEOSERVER_EXT_PORT: "8600"
  GEOSERVER_INITIAL_MEMORY: "2G"
  GEOSERVER_MAXIMUM_MEMORY: "4G"
  GEOWEBCACHE_CACHE_DIR: "/opt/geoserver/data_dir/gwc"
  INITIAL_MEMORY: "2G"
  MAX_FILTER_RULES: "20"
  MAXIMUM_MEMORY: "4G"
  OPTIMIZE_LINE_WIDTH: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: indrz-db
type: Opaque
stringData:
  DB: "indrz"
  EXT_PORT: "5435"
  HOST: "indrz-db.svc"
  PASS: "TODO"
  PORT: "5432"
  USER: "indrz"
---
apiVersion: v1
kind: Secret
metadata:
  name: indrz-common
type: Opaque
stringData:
  ENV_TYPE: "prod"
  PROJECT_NAME: "indrz-api"
  TIMEZONE: "Europe/Vienna"
  WEB_FOLDER: "/var/www"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indrz-nginx
data:
  default.conf: |
      server {
          listen      80 default_server;
          server_name _;

          root /var/www/indrz;
          include /etc/nginx/allowed.conf;
          include /etc/nginx/locations.conf;
      }
